### ISSUE TITLE
cannot import name 'triu' from 'scipy.linalg'

### ISSUE THREAD

**Issue by kakaisi** [aertslab/pycisTopic#135]
**Describe the bug**
I downloaded and installed the pycistopic package according to the requirements of the official document, but the incompatibility of the scipy package still occurred when the theme model was processed. However, when I looked at the terminal, there was no incompatible red font prompt. So I hope we can get some help. Thank you

**To Reproduce**
when i run model,The code is as follows.

os.environ['MALLET_MEMORY'] = '200G'
from pycisTopic.lda_models import run_cgs_models_mallet
# Configure path Mallet
mallet_path="Mallet-202108/bin/mallet"
# Run models
models=run_cgs_models_mallet(
    cistopic_obj,
    n_topics=[2, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
    n_cpu=40,
    n_iter=500,
    random_state=555,
    alpha=50,
    alpha_by_topic=True,
    eta=0.1,
    eta_by_topic=False,
    tmp_path="/home/fang/4t/lcw/pycistopic/mallet/tutorial/",
    save_path="/home/fang/4t/lcw/pycistopic/mallet/tutorial/",
    mallet_path=mallet_path,
)

**Error output**
ImportError: cannot import name 'triu' from 'scipy.linalg' (/home/fang/4t/conda/envs/scenicplus/lib/python3.11/site-packages/scipy/linalg/__init__.py)

Could you help me?

**Comment by danielduyvo** [comment]
`triu` has been deprecated from `scipy.linalg` since version 1.11.0,  so downgrading the scipy version would fix this particular import error.
