### ISSUE TITLE
Error when running run_cgs_models_mallet

### ISSUE THREAD

**Issue by EddieLv** [aertslab/pycisTopic#137]
**Describe the bug**
command '['/home/biogenger/Biosoftwares/Mallet-202108/bin/mallet', 'train-topics', '--input', '/media/biogenger/D/tmp/corpus.mallet', '--num-topics', '10', '--alpha', '50', '--beta', '0.1', '--optimize-interval', '0', '--num-threads', '4', '--output-state', '/media/biogenger/D/tmp/f5dd8b_state.mallet.gz', '--output-doc-topics', '/media/biogenger/D/tmp/f5dd8b_doctopics.txt', '--output-topic-keys', '/media/biogenger/D/tmp/f5dd8b_topickeys.txt', '--num-iterations', '500', '--inferencer-filename', '/media/biogenger/D/tmp/f5dd8b_inferencer.mallet', '--doc-topics-threshold', '0.0', '--random-seed', '555']' return with error (code 134): b'Mallet LDA: 10 topics, 4 topic bits, 1111 topic mask\nData loaded.\nmax tokens: 182472\ntotal tokens: 46261622\n<10> LL/token: -14.41878\n<20> LL/token: -13.68493\n<30> LL/token: -13.49095\n<40> LL/token: -13.41376\n\n0\t5\t411877 398073 30079 163439 351448 369297 371956 191777 187835 94337 297894 275631 418699 232388 164343 68994 275158 117303 143425 32571 \n1\t5\t64175 65197 254352 428138 296846 310876 229430 384271 208021 117051 371725 337763 229513 299899 139844 117532 64123 66043 397010 387203 \n2\t5\t229979 28597 32272 250947 338737 67442 96361 323491 164061 312360 273903 68651 163602 325071 311243 352118 228280 227100 353714 298276 \n3\t5\t69629 419161 98287 32902 31625 33598 253227 116989 211624 120025 323459 324808 191156 385159 275082 31755 210882 189425 276499 277116 \n4\t5\t26459 250229 274451 ...

**To Reproduce**
os.environ['MALLET_MEMORY'] = '64G'
from pycisTopic.lda_models import run_cgs_models_mallet
# Configure path Mallet
mallet_path="/home/biogenger/Biosoftwares/Mallet-202108/bin/mallet"
# Run models
models=run_cgs_models_mallet(
    cistopic_obj,
    n_topics=[2, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100],
    n_cpu=4,
    n_iter=500,
    random_state=555,
    alpha=50,
    alpha_by_topic=True,
    eta=0.1,
    eta_by_topic=False,
    tmp_path=tmp_dir,
    save_path="/media/biogenger/D/scenicplus/10x_brain/out_pycisTopic/cgs_models",
    mallet_path=mallet_path,
)

**Error output**
[hs_err_pid2479701.log](https://github.com/aertslab/pycisTopic/files/15142185/hs_err_pid2479701.log)

**Version (please complete the following information):**
 - Python: [e.g. Python 3.11]

**Comment by ghuls** [comment]
Can you try with a different Java version? e.g. `java 1.8.x`

**Comment by EddieLv** [comment]
It works! Thank you~
