### ISSUE TITLE
Groupby steps when handling fragments [PERFORMANCE]

### ISSUE THREAD

**Issue by cbravo93** [aertslab/pycisTopic#14]
**What type of problem are you experiencing and which function is you problem related too**
When working with fragments files there are several steps where we use groupby operations to get matrices with barcodes and regions (or cut sites positions), which are demanding excessive memory. These occurs in qc functions (TSS, FRIP) and in the creation of cisTopicObjects. Also, but less problematic, in barcode_rank_plot, duplicate_rate and insert_size_distributions (here it is only use to aggregate scores by barcode and sum, not to make a matrix).

**Is this problem data set related? If so, provide information on the problematic data set**
The performance of these steps is limited with medium-to-large data sets, and memory usage scales rather exponentially.

**Have you identified the step of set of steps that lead to this problem in the function?**
Here I will report the steps where groupby is used to create count matrices, but solutions may be applicable to barcode_rank_plot, duplicate_rate and insert_size_distributions too.
- frip: qc.py: 640-641
- get_tss_matrix: utils.py: 327-328
- create_cistopic_object_from_fragments: cistopic_class.py: 774-791

**Describe alternatives you've considered**
Some solutions we have discussed:
- Modin
- Polars
- Vaex

**Additional context**

**Version information**
Report versions of modules relevant to this error

pycisTopic: 0.1.dev119+g4af8f57.d20210308

**Comment by klgoss** [comment]
Any update on this? I'm trying to run pycisTopic on a large dataset (~114,000 cells) and have maxed out the memory requirement on HPC (700GB) and it still crashes. Any insight appreciated!

**Comment by ghuls** [comment]
@klgoss The polars branch is functional now for end-users:

https://pycistopic.readthedocs.io/en/polars/notebooks/human_cerebellum.html#QC
