### ISSUE TITLE
Imputed accessibility calculation [PERFORMANCE]

### ISSUE THREAD

**Issue by cbravo93** [aertslab/pycisTopic#15]
**What type of problem are you experiencing and which function is you problem related too**
Excessive memory usage when computing the imputed accessibility with impute_accessibility

**Is this problem data set related? If so, provide information on the problematic data set**
I have experienced the problem in my largest data set, with 250K cells and 800K regions; but definitely this can be very problematic for people with less resources

**Have you identified the step of set of steps that lead to this problem in the function?**
Matrix multiplication and scaling (246-270). The biggest issue is that we are multiplying probabilities, so the matrix is dense (no 0).

**Describe alternatives you've considered**
- Calculate it per chunks
- Round probabilities before matrix multiplication in topic-region distributions (which threshold?)
- Numba

**Additional context**

**Version information**
Report versions of modules relevant to this error

**Comment by WangRong423** [comment]
@cbravo93  Hi,I have the same problem as you（my data set with 220K cells and 500K regions）, unfortunately, the maximum running memory on my linux system is only 1TB. I cannot carry out the further analysis. Do you have a detailed solution? Look forward to your sharing.
