### ISSUE TITLE
Error while running run_cgs_models_mallet()

### ISSUE THREAD

**Issue by skoturan** [aertslab/pycisTopic#164]
Hi, I'm running topic modelling function in cistopic in the new SCENIC+ with this:

`os.environ['MALLET_MEMORY'] = '200G'`
`from pycisTopic.lda_models import run_cgs_models_mallet`
`mallet_path="/filepath/Mallet-202108/bin/mallet"`

`models=run_cgs_models_mallet(cistopic_obj,
    n_topics=[2, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50],
    n_cpu=12,
    n_iter=500,
    random_state=555,
    alpha=50,
    alpha_by_topic=True,
    eta=0.1,
    eta_by_topic=False,
    tmp_path="tmpdir",
    save_path="none",
    mallet_path=mallet_path,
)`

I keep getting this error:

`2024-09-09 11:33:00,119 cisTopic     INFO     Formatting input to corpus
2024-09-09 11:33:00,124 cisTopic     INFO     Running model with 2 topics
2024-09-09 11:33:00,125 LDAMalletWrapper INFO     Serializing temporary corpus to filepath/corpus.txt
Unexpected exception formatting exception. Falling back to standard exception
.
.
.
AttributeError: 'Source' object has no attribute 'asttext'`

Could you please help to resolve this?

Thanks

**Comment by SeppeDeWinter** [comment]
Hi @skoturan 

This seems to be an issue with mallet.
Which version do you have?

All the best,

Seppe

**Comment by skoturan** [comment]
Hi, thanks for replying!

It was a permission issue for the mallet file- I executed `chmod` and it's running now!
