### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by juhi-ku** [aertslab/pycisTopic#173]
I am constantly facing error in installation even though I have updated the python and lda. It still throws an error. Can you please tell me where is the error?

**ERROR: Ignored the following versions that require a different python version: 0.5.12 Requires-Python >=3.7,<3.12; 0.5.13 Requires-Python >=3.7,<3.12; 3.0.0 Requires-Python >=3.9,<=3.12
ERROR: Could not find a version that satisfies the requirement lda==3.0.0 (from scenicplus) (from versions: 0.1.0, 0.2.0, 0.2.1rc0, 0.3.0, 0.3.1, 0.3.2, 1.0.0, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 2.0.0, 3.0.1, 3.0.2)
ERROR: No matching distribution found for lda==3.0.0**

**Comment by Stack7** [comment]
I solved the issue in 2 steps: the first was:
` python3.11 -m pip install lda==3.0.0`
the second:
`python3.11 -m pip install .`
Considering that I am installing SCENIC+ : https://github.com/aertslab/scenicplus in a conda enviroment with python version 3.11 after a git clone of the repo
