### ISSUE TITLE
No module named 'pycisTopic.gene_activity'

### ISSUE THREAD

**Issue by Melody-cell** [aertslab/pycisTopic#191]
Hi, in this version, i can't load gene_activity,
![image](https://github.com/user-attachments/assets/cb821c4d-921e-41bd-b456-66cb548e4ab9)
Did anyone know how to solve it ?

**Comment by Melody-cell** [comment]
@SeppeDeWinter Hi,
when i run this , it appeared this error:
![image](https://github.com/user-attachments/assets/56a6d7d6-41f9-4912-aa3a-ea9391162486)
i don't know why, cause last time i ran this, it finished smoothly.

**Comment by SeppeDeWinter** [comment]
Hi @Melody-cell 

Do you happen to have a file named "pycisTopic" in your working directory? 

All the best,

Seppe

**Comment by Melody-cell** [comment]
Hi, @SeppeDeWinter ,
yes, i know how to fix it now,
thank you very much.
