### ISSUE TITLE
Dependency error while installing pycistopic

### ISSUE THREAD

**Issue by matthieuheitz** [aertslab/pycisTopic#33]
**Describe the bug**
Dependency error while installing pycistopic. Happens when running either `pip install .` or `pip install -e .`

**To Reproduce**
```
git clone https://github.com/aertslab/pycisTopic.git
cd pycisTopic
pip install .
```

**Error output**

> ERROR: Cannot install pycisTopic and pycistopic==1.0.1 because these package versions have conflicting dependencies. 
> 
> The conflict is caused by:                                                                            
>     pycistopic 1.0.1 depends on pyscenic 0.12.0 (from git+https://github.com/aertslab/pySCENIC@master)
>     loomxpy 0.4.2 depends on pyscenic<0.12.0 and >=0.11.1                                             
> 

**Version (please complete the following information):**
 - Python 3.8.10
 - pip 22.1

**Comment by cbravo93** [comment]
Hi @matthieuheitz !

Thanks for noticing, we just updated pySCENIC and loomxpy a few hours ago in pip, but hadn't pushed the changes to the loomxpy repo, which should have caused your issue. It should work now, can you try to install again?

Sorry, we will be doing some changes this days as well, next week it should be more stable :)

Carmen
