### ISSUE TITLE
Installation - Cistopic

### ISSUE THREAD

**Issue by Sayyam-Shah** [aertslab/pycisTopic#38]
Hello,

Thank you so much for the amazing tool. I'm excited to use it. However, I am getting installation problems. I included the error below. 

Building wheels for collected packages: pycisTopic, annoy
  Building wheel for pycisTopic (setup.py) ... done
  Created wheel for pycisTopic: filename=pycisTopic-1.0.2.dev9+gaf3977c-py3-none-any.whl size=93786 sha256=7fd73da5c063af0c55166c4226b65cbd0d604cfc51d8519f93886812f4bbe8ff
  Stored in directory: /tmp/pip-ephem-wheel-cache-n9q03_td/wheels/62/64/82/580e6ee56bd55c662eae26c715f7a5e51d1c149c0775b38171
  Building wheel for annoy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /cluster/tools/software/centos7/python/3.7.2/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-wxli26ux
       cwd: /tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/
  Complete output (18 lines):
  /cluster/home/t114108uhn/.local/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    SetuptoolsDeprecationWarning,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-cpython-37
  creating build/lib.linux-x86_64-cpython-37/annoy
  copying annoy/__init__.py -> build/lib.linux-x86_64-cpython-37/annoy
  copying annoy/__init__.pyi -> build/lib.linux-x86_64-cpython-37/annoy
  copying annoy/py.typed -> build/lib.linux-x86_64-cpython-37/annoy
  running build_ext
  building 'annoy.annoylib' extension
  creating build/temp.linux-x86_64-cpython-37
  creating build/temp.linux-x86_64-cpython-37/src
  gcc -pthread -B /cluster/tools/software/centos7/python/3.7.2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/cluster/tools/software/centos7/python/3.7.2/include/python3.7m -c src/annoymodule.cc -o build/temp.linux-x86_64-cpython-37/src/annoymodule.o -D_CRT_SECURE_NO_WARNINGS -fpermissive -march=native -O3 -ffast-math -fno-associative-math -DANNOYLIB_MULTITHREADED_BUILD -std=c++14
  gcc: error: unrecognized command line option ‘-std=c++14’
  error: command '/usr/bin/gcc' failed with exit code 1

  ERROR: Failed building wheel for annoy
  Running setup.py clean for annoy
Successfully built pycisTopic
Failed to build annoy
Installing collected packages: annoy, tmtoolkit, scrublet, scanorama, python-Levenshtein, python-igraph, pyfasta, pyBigWig, polars, papermill, macs2, lxml, lda, ipympl, gensim, bs4, bbknn, pycisTopic
    Running setup.py install for annoy ... error
    ERROR: Command errored out with exit status 1:
     command: /cluster/tools/software/centos7/python/3.7.2/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u1qa43sm/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /cluster/home/t114108uhn/.local/include/python3.7m/annoy
         cwd: /tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/
    Complete output (20 lines):
    /cluster/home/t114108uhn/.local/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      SetuptoolsDeprecationWarning,
    running install
    /cluster/home/.local/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-cpython-37
    creating build/lib.linux-x86_64-cpython-37/annoy
    copying annoy/__init__.py -> build/lib.linux-x86_64-cpython-37/annoy
    copying annoy/__init__.pyi -> build/lib.linux-x86_64-cpython-37/annoy
    copying annoy/py.typed -> build/lib.linux-x86_64-cpython-37/annoy
    running build_ext
    building 'annoy.annoylib' extension
    creating build/temp.linux-x86_64-cpython-37
    creating build/temp.linux-x86_64-cpython-37/src
    gcc -pthread -B /cluster/tools/software/centos7/python/3.7.2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/cluster/tools/software/centos7/python/3.7.2/include/python3.7m -c src/annoymodule.cc -o build/temp.linux-x86_64-cpython-37/src/annoymodule.o -D_CRT_SECURE_NO_WARNINGS -fpermissive -march=native -O3 -ffast-math -fno-associative-math -DANNOYLIB_MULTITHREADED_BUILD -std=c++14
    gcc: error: unrecognized command line option ‘-std=c++14’
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /cluster/tools/software/centos7/python/3.7.2/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/setup.py'"'"'; __file__='"'"'/tmp/pip-install-hf7srfdb/annoy_2eaee1864c66418e8b151b9e08b045e3/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-u1qa43sm/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /cluster/home/.local/include/python3.7m/annoy Check the logs for full command output

May you please help me debug this? It seems there is some conflict with the annoy tool. I am installing this on an HPC cluster

**Comment by cbravo93** [comment]
Hi!

Do you get the error with `pip install setuptools`?

C
