### ISSUE TITLE
cannot create a cisTopic object from a sparse matrix

### ISSUE THREAD

**Issue by yamamotoryo** [aertslab/pycisTopic#40]
HI 
Thank you for your contribution to single cell analysis field! 
I'm trying to create a cisTopic obj by transferring from a Signac object.
I made an anndata from Signac peaks assays. 
adata.X is a sparse matrix corresponding to a raw count of peaks count matrix.
**To Reproduce**
```
cistopic_obj=create_cistopic_object(fragment_matrix=adata.X.T.astype(dtype=int),
                                    cell_names=adata.obs_names.tolist(),
                                    region_names=adata.var_names.tolist(),
                                    path_to_fragments=os.path.join(work_dir,'10x/outs/atac_fragments.tsv.gz'),
                                    split_pattern='_')
```
**Error output**
2022-09-19 09:41:37,455 cisTopic     INFO     Creating CistopicObject
Traceback (most recent call last):

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/scipy/sparse/_base.py", line 337, in __bool__
    raise ValueError("The truth value of an array with more than one "

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/var/folders/59/cxr2yt4926jc95n5w2mtz32r0000gn/T/ipykernel_62124/4185193884.py", line 1, in <module>
    cistopic_obj=create_cistopic_object(fragment_matrix=peaks_adata.X.T[:,0:4963].astype(dtype=int),

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pycisTopic/cistopic_class.py", line 592, in create_cistopic_object
    selected_regions = non_zero_rows(binary_matrix)

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/pycisTopic/utils.py", line 43, in non_zero_rows
    return np.nonzero(np.count_nonzero(X, axis=1))[0]

  File "<__array_function__ internals>", line 5, in count_nonzero

  File "/Users/jack/opt/anaconda3/lib/python3.9/site-packages/numpy/core/numeric.py", line 493, in count_nonzero
    a_bool = a.astype(np.bool_, copy=False)

ValueError: setting an array element with a sequence.

**Expected behavior**
Successful creating object

**Screenshots**
adata.var_names
![Screen Shot 2022-09-19 at 9 56 37 AM](https://user-images.githubusercontent.com/43850178/191034362-58bd5290-51a9-4356-8c27-8b0041ddec7d.png)
adata.obs_names
![Screen Shot 2022-09-19 at 9 57 36 AM](https://user-images.githubusercontent.com/43850178/191034568-0e153cb8-260f-4821-9b85-ced850c57e61.png)

**Version (please complete the following information):**
 - Python: Python 3.9.7
 - numpy 1.20.3 py39h4b4dc7a_0 anaconda
 
I appreciate it if you would give me any help.

Sicerely,
Ryosuke

**Comment by yamamotoryo** [comment]
Thank you, @cbravo93 !

I changed the separator of region names. It failed again using the sparse matrix, but it succeeded after converting the sparse matrix to a data frame.
I appreciate your kindness.

**Comment by klgoss** [comment]
Am having a similar issue when trying to create a cistopic object from a sparse matrix. I’m using `cistopic_obj = create_cistopic_object(fragment_matrix=count_mat, path_to_blacklist=path_to_blacklist)` and get the following error: “ValueError: invalid literal for int() with base 10: 'chr1:10003-10355’” 

Does anyone know how to fix this?

**Comment by YH-Zheng** [comment]
@cbravo93 Hi, my atac data is saved in anndata. When I transposed the sparse matrix adata.X and created a cistopic object, I encountered an error: "setting an array element with a sequence."
`cistopic_obj = create_cistopic_object(fragment_matrix=atac.X.transpose(), 
                                      cell_names=atac.obs_names.tolist(),
                                    region_names=atac.var_names.tolist())`
However, when converting the sparse matrix into a sparse pandas dataframe and then creating a cistopic object, the memory usage is extremely large and the data no longer seems to be sparse.

**Comment by AnasAnsari123** [comment]
I am also having a same error when creating a cisobject.  
cistopic_obj = create_cistopic_object(fragment_matrix=count_matrix) , 
and the error I am getting is 
ValueError: invalid literal for int() with base 10: 'Chr1-10002-10434'


Does anybody have solved this yet?

**Comment by SeppeDeWinter** [comment]
Hi @AnasAnsari123 

Your region names are not formatted correctly, pycisTopic assumes the following formatting "chr:start-end" (you have dashes between the chromosome name and the start position, while this should be a `:`). 

Best,

Seppe

**Comment by 09oulin** [comment]
> [@cbravo93](https://github.com/cbravo93) Hi, my atac data is saved in anndata. When I transposed the sparse matrix adata.X and created a cistopic object, I encountered an error: "setting an array element with a sequence." `cistopic_obj = create_cistopic_object(fragment_matrix=atac.X.transpose(), cell_names=atac.obs_names.tolist(), region_names=atac.var_names.tolist())` However, when converting the sparse matrix into a sparse pandas dataframe and then creating a cistopic object, the memory usage is extremely large and the data no longer seems to be sparse.

Yeah, I have faced the same problem. Have you solved it? I appreciate it if you would give me any help.
