### ISSUE TITLE
Bug report [cisTopicLDAModel] on utils.py

### ISSUE THREAD

**Issue by rochevin** [aertslab/pycisTopic#43]
Hello,
I'm trying to convert a cistopic project into a pycistopic project, based on the code source you gave here : https://pycistopic.readthedocs.io/en/latest/faqs.html

I've got some error when I try to launch your function `load_cisTopic_model` :

`NameError: name 'cisTopicLDAModel' is not defined`

the code here : https://github.com/aertslab/pycisTopic/blob/master/pycisTopic/utils.py#L175

declare `cisTopicLDAModel`, which is not defined.

https://github.com/aertslab/pycisTopic/blob/master/pycisTopic/lda_models.py#L32 define `CistopicLDAModel`, which capital C

I think it cause the error on my code.
Thanks for your packages, it's great,
Best regards

**Comment by rkelly712** [comment]
@rochevin Just wondering if you found a workaround? I've run into the same issue.

Thanks in advance.

**Comment by cbravo93** [comment]
It was indeed a typo, should be capital C. It is fixed.

C

**Comment by sid5427** [comment]
Good day 

Unfortunately I also seem to be having the same bug while trying to import my R cistopic model into scenic+/pycistopic

 I updated to the latest version on github just to be sure- 
```
import pycisTopic
pycisTopic.__version__
'1.0.2.dev10+g326fbf2'
```

I get this error while trying to use the load_cisTopic_model() function


**model = load_cisTopic_model("model_to_pycisTopic/")**
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/var/folders/sm/rsx_yp0n66x0m9y8gqc2kxj00000gq/T/ipykernel_48656/2488105293.py in <module>
      1 ## 2. Add model
      2 from pycisTopic.utils import *
----> 3 model = load_cisTopic_model("model_to_pycisTopic/")

/opt/anaconda3/envs/Py_3_8_env/lib/python3.8/site-packages/pycisTopic/utils.py in load_cisTopic_model(path_to_cisTopic_model_matrices)
    173     topic_region = topic_region.T
    174     parameters = None
--> 175     model = cisTopicLDAModel(
    176         metrics, coherence, marg_topic, topic_ass, cell_topic, topic_region, parameters
    177     )

NameError: name 'cisTopicLDAModel' is not defined
```

If I try calling the cisTopicLDAModel() function on it's own -
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/var/folders/sm/rsx_yp0n66x0m9y8gqc2kxj00000gq/T/ipykernel_51238/2329119706.py in <module>
----> 1 CisTopicLDAModel()

NameError: name 'CisTopicLDAModel' is not defined
```

After looking at the documentation posted above - I even tried changing both C and T to lowercase, both upper case, and C upper case with t lowercase - and vice versa - same issue.

Would appreciate if you could look into this.

**Comment by cbravo93** [comment]
Solved! Left the middle upper T accidentally, sorry!
