### ISSUE TITLE
transform new data

### ISSUE THREAD

**Issue by camiel-m** [aertslab/pycisTopic#44]
Hi,

I was looking for a way to transform/predict new data points using a trained model. Briefly I downsampled my data to train a model and now want to get topic assignments for the remaining data, but I couldn't find a convenient way to do so within the pycistopic class (maybe I missed it). I suspect there is some normalization going on in pycistopic that takes some time to figure out if ones wants to predict topics for new data manually as a simple multiplication didn't yield the expected topic distribution in my case. I think a feature like the '.transform()' employed in sklearn would be very useful.

Camiel

**Comment by cbravo93** [comment]
Hi @camiel-m !

We currently don't have a function for it but it is possible to do it (see Methods in https://www.embopress.org/doi/full/10.15252/msb.20209438, Fig S11A):
```
Additionally, we projected the FAC-sorted single-cell profiles (Optix-GFP+ and sens-GFP+) with at least 70% of the fragments within regulatory regions into the existing topic space. Briefly, the topic-cell distributions of the new cells were estimated by multiplying the binary count matrix (cell-regions) by the region-topic distributions of the existing models. The estimated topic-cell contributions were merged with the topic-cell distributions of the original cells and normalized (by Z-Score), and batch effects were corrected with Harmony (v1.0)
```
I can share the R code for it, I'll also add a function for this in a few days since we are in the same situation for some projects.

Cheers!

C
