### ISSUE TITLE
Cistopic object with NaN for a lot of criteria

### ISSUE THREAD

**Issue by tu4n-p** [aertslab/pycisTopic#45]
Hi there, I'm analyzing Dmel scATACseq for embrogenesis with pycistopic. Things went well until I checked cistopic object and all of the  Log_total_nr_frag | Log_unique_nr_frag | Total_nr_frag | Unique_nr_frag | Dupl_nr_frag | Dupl_rate | Total_nr_frag_in_regions | Unique_nr_frag_in_regions | FRIP | TSS_enrichment were NaN for all rows. 
I was wondering if there could possibly anything that I can work around this? Thank you, 

<img width="476" alt="Screen Shot 2022-11-10 at 1 17 53 PM" src="https://user-images.githubusercontent.com/76016401/201175430-fe4e1fd9-d0ad-42df-a4a4-fbfc7f3279e8.png">

<img width="900" alt="Screen Shot 2022-11-10 at 1 18 10 PM" src="https://user-images.githubusercontent.com/76016401/201175466-67d1f758-6258-4db1-87bd-2fbc0bba680c.png">

**Describe the bug**

**To Reproduce**
Commands relevant to reproduce the error.

**Error output**
Paste the entire output of the command, including log information prior to the error.

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem or show the format of the input data for the command/s.

**Version (please complete the following information):**
 - Python: [e.g. Python 3.7.4]
 - If a bug is related to another module [e.g. matplotlib 3.3.9]

**Additional context**

**Comment by cbravo93** [comment]
Hi @tu4n-p !

How did you initialize the cistopic object? Did you add the cell data externally (add_cell_data)? Can you show the barcode names?


C

**Comment by tu4n-p** [comment]
So I followed Single_sample_workflow where I started out with annotated ATAC fragments from my lab (we don't have co-assayed RNA seq). When I did quality control, I was able to plot out TSS and FRiP 
<img width="1394" alt="Screen Shot 2022-11-26 at 12 17 32 AM" src="https://user-images.githubusercontent.com/76016401/204074834-ac593fc3-af5e-428d-87c0-2839f2eb19b8.png">
but  when I added cell_meta using cistopic_obj.add_cell_data(cell_data, split_pattern='-') , I ran into the NaN problem.
This is the code I used to create cistopic obj:
<img width="1004" alt="Screen Shot 2022-11-26 at 1 43 59 AM" src="https://user-images.githubusercontent.com/76016401/204076052-14522462-0d0f-4f3c-8d83-b82f41945aae.png">

This is the cell_data I used 

<img width="1394" alt="Screen Shot 2022-11-26 at 12 17 32 AM" src="https://user-images.githubusercontent.com/76016401/204074328-e9b1c9e6-3d62-446d-85f0-49fa9c29917b.png">
One barcode row:
<img width="979" alt="Screen Shot 2022-11-26 at 1 41 48 AM" src="https://user-images.githubusercontent.com/76016401/204075958-d569d12b-51ca-4903-88f9-f11982f9a087.png">
<img width="886" alt="Screen Shot 2022-11-26 at 1 41 59 AM" src="https://user-images.githubusercontent.com/76016401/204075960-f2ddeff2-3534-4648-8cf6-95cf9c84b76a.png">

**Comment by cbravo93** [comment]
Sorry for the lay response @tu4n-p ! You have to add -10x_multiome_brain to the index names in the metadata.

C

**Comment by yojetsharma** [comment]
Were you able to solve this?
