### ISSUE TITLE
Bug report [BUG]

### ISSUE THREAD

**Issue by rkelly712** [aertslab/pycisTopic#47]
Hi,

I've scATAC-seq data processed in ArchR and i'm looking to convert it as described here:
https://pycistopic.readthedocs.io/en/latest/faqs.html

I'd recently had an issue (#43) resolved so i re-downloaded the SCENIC+ package as described for a conda environment but i've run into a new issue. I'm unsure if this is to do with re-downloading SCENIC+ or something new as i've been able to run this code successfully in the past.

I've most likely just messed up the download somehow but it'd be great to know why this issue is popping up.

Thanks in advance.

- pycistopic version: 1.0.2.dev10+g326fbf2
- Python version: 3.8

Code run:
---------------------------------------------------------------------------
`import pycisTopic`
`from pycisTopic.cistopic_class import *`

Error below:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In [2], line 3
      1 import pycisTopic
      2 ## 1. Initialize cisTopic object
----> 3 from pycisTopic.cistopic_class import *

File /gpfs/gsfs6/users/HPC/conda/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/cistopic_class.py:13
     10 import sklearn.preprocessing as sp
     11 from scipy import sparse
---> 13 from .lda_models import *
     14 from .utils import *
     16 dtype = pd.SparseDtype(int, fill_value=0)

File /gpfs/gsfs6/users/HPC/conda/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/lda_models.py:29
     26 from scipy import sparse
     28 from pycisTopic.cistopic_class import *
---> 29 from pycisTopic.utils import *
     32 class CistopicLDAModel:
     33     """
     34     cisTopic LDA model class
     35 
   (...)
     69     Arun, R., Suresh, V., Madhavan, C. V., & Murthy, M. N. (2010). On finding the natural number of topics with latent dirichlet allocation: Some observations. In Pacific-Asia conference on knowledge discovery and data mining (pp. 391-402). Springer, Berlin, Heidelberg.
     70     """

File /gpfs/gsfs6/users/HPC/conda/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/utils.py:15
     13 from PIL import Image
     14 from scipy import sparse
---> 15 from pycisTopic.lda_models import CistopicLDAModel
     18 def region_names_to_coordinates(region_names):
     19     chrom = pd.DataFrame([i.split(":", 1)[0] for i in region_names if ":" in i])

ImportError: cannot import name 'CistopicLDAModel' from partially initialized module 'pycisTopic.lda_models' (most likely due to a circular import) (/gpfs/gsfs6/users/HPC/conda/envs/scenicplus/lib/python3.8/site-packages/pycisTopic/lda_models.py)

**Comment by cbravo93** [comment]
Should be fixed now :)

**Comment by PragmatistWu** [comment]
Hi, thanks for developing such a useful tools!
I encountered the same error as mentioned above. So the solution is supposed to be re-downloading the Scenic+ package?  
Thanks in advance.

**· pycistopic version: 1.0.2.dev10+g326fbf2.d20221128
· python version: python3.8**
