### ISSUE TITLE
`peak_calling` logger fails if `bed_paths` created from integers [BUG]

### ISSUE THREAD

**Issue by dburkhardt** [aertslab/pycisTopic#61]
**Describe the bug**
If you calculate pseudobulk from `export_pseudobulk` passing `variable` using a metadata column that can be interpreted as `int`, then the `bed_paths` dict has `int` for keys. 

This then breaks the logger because string formatting is done incorrectly.

```
File /srv/conda/envs/saturn/lib/python3.9/site-packages/pycisTopic/pseudobulk_peak_calling.py:711, in MACSCallPeak.load_narrow_peak(self)
    706 def load_narrow_peak(self):
    707     """
    708     Load MACS2 narrow peak files as :class:`pr.PyRanges`.
    709     """
    710     narrow_peak = pd.read_csv(
--> 711         os.path.join(self.outdir, self.name + "_peaks.narrowPeak"),
    712         sep="\t",
    713         header=None,
    714     )
    715     narrow_peak.columns = [
    716         "Chromosome",
    717         "Start",
   (...)
    725         "Summit",
    726     ]
    727     narrow_peak_pr = pr.PyRanges(narrow_peak)

TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

here, `self.name` is from the `bed_paths` dict, so it can be ints. 

This happens all the time if you run pseudobulk on e.g. output from `sc.tl.leiden`

**Additional context**
Honestly, the real fix is not to do string formatting by `+` 'ing class variables to strings. Just do inline string formatting with `f"{variable} my favorite text"`.

**Comment by cbravo93** [comment]
Hi @dburkhardt !

Indeed, we spotted the same a few days back. A quick fix is to convert the keys to str:

```
d = {str(x):d[x] for x in d.keys()}
```

Thanks for the pull request, will merge it shortly :)

C
