### ISSUE TITLE
Topic modelling not finishing after 36 hours for 170,000 cell dataset

### ISSUE THREAD

**Issue by dburkhardt** [aertslab/pycisTopic#63]
Do you have any guidance for how long it should take to run `pycisTopic.cistopic_class.run_cgs_models` on 170,000 cells? It's currently taking me more than 36 hours on a machine with 1TB of RAM and 64 CPUs (although only 9 cores seem to be being used). I also have a subsampled 30,000 cell dataset that hasn't finished in 17h. Each dataset has ~220,000 peaks.

Sometimes this step just fails. Is that expected? Do you have any runtime benchmarks?

**Comment by cbravo93** [comment]
Hi!

For large data sets we recommend to use `run_cgs_models_mallet`. The running time depends on the number of models, the number of cells/regions and the coverage of the data. As reference, here is the time in seconds as a function of cells (up to 25K cells) and different coverages (3K, 10K and 20K fragments per cell).

<img width="455" alt="image" src="https://user-images.githubusercontent.com/19205518/216382789-ca14444a-72af-4505-b35c-3ec6b143fe06.png">

You can also double check if there could be other issues using the test data here: https://pycistopic.readthedocs.io/en/latest/Toy_melanoma-RTD.html

Cheers!

C

**Comment by dburkhardt** [comment]
What is the x-axis of the first two plots and the units for the third?

**Comment by cbravo93** [comment]
Cells (sorry, screenshot from larger plot :))

**Comment by dburkhardt** [comment]
Okay then units for the y-axis?

**Comment by cbravo93** [comment]
Time in seconds

**Comment by dburkhardt** [comment]
Got it, thanks!
