### ISSUE TITLE
`find_diff_features`: `ValueError`

### ISSUE THREAD

**Issue by alexlenail** [aertslab/pycisTopic#68]
```
creating markers_dict
Traceback (most recent call last):
  File "/home/lenail/miniconda3/envs/py39/lib/python3.9/site-packages/scipy/sparse/_base.py", line 337, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../ATAC/pyCisTopic_atac.py", line 448, in <module>
    impute4('hippo')
  File ".../ATAC/pyCisTopic_atac.py", line 423, in impute4
    markers_dict = find_diff_features(cistopic_obj,
  File "/home/lenail/miniconda3/envs/py39/lib/python3.9/site-packages/pycisTopic/diff_features.py", line 662, in find_diff_features
    subset_imputed_features_obj = imputed_features_obj.subset(
  File "/home/lenail/miniconda3/envs/py39/lib/python3.9/site-packages/pycisTopic/diff_features.py", line 106, in subset
    features_index = non_zero_rows(mtx)
  File "/home/lenail/miniconda3/envs/py39/lib/python3.9/site-packages/pycisTopic/utils.py", line 43, in non_zero_rows
    return np.nonzero(np.count_nonzero(X, axis=1))[0]
  File "<__array_function__ internals>", line 180, in count_nonzero
  File "/home/lenail/miniconda3/envs/py39/lib/python3.9/site-packages/numpy/core/numeric.py", line 500, in count_nonzero
    a_bool = a.astype(np.bool_, copy=False)
ValueError: setting an array element with a sequence.
```

https://github.com/aertslab/pycisTopic/blob/219225df56b32738d82cd14532b187a1483de04f/pycisTopic/diff_features.py#L106

Possibilities: 

1. Unlike the [tutorial](https://scenicplus.readthedocs.io/en/latest/pbmc_multiome_tutorial.html), I dumped the normalized object to a pickle file in one job and then read it in the next. The tutorial reads: 

```
imputed_acc_obj = impute_accessibility(cistopic_obj, selected_cells=None, selected_regions=None, scale_factor=10**6)
normalized_imputed_acc_obj = normalize_scores(imputed_acc_obj, scale_factor=10**4)
variable_regions = find_highly_variable_features(normalized_imputed_acc_obj, plot = False)
```

But I did: 

```
imputed_acc_obj = impute_accessibility(cistopic_obj, selected_cells=None, selected_regions=None, scale_factor=10**6)
pickle.dump(imputed_acc_obj)
```
then:
```
imputed_acc_obj = pickle.load(imputed_acc_obj_path)
normalized_imputed_acc_obj = normalize_scores(imputed_acc_obj, scale_factor=10**4)
pickle.dump(normalized_imputed_acc_obj)
```
then:
```
normalized_imputed_acc_obj = pickle.load(normalized_imputed_acc_obj_path)
variable_regions = find_highly_variable_features(normalized_imputed_acc_obj, plot = False)
```

2.  I sparsified my imputed_acc_obj post-hoc. The function does: 

https://github.com/aertslab/pycisTopic/blob/219225df56b32738d82cd14532b187a1483de04f/pycisTopic/diff_features.py#L398-L400

but I did: 

```
imputed_acc_obj = impute_accessibility(cistopic_obj, selected_cells=None, selected_regions=None, scale_factor=10**6, sparsity_thr=0.99)
imputed_acc_obj.mtx = sparse.csr_matrix(imputed_acc_obj.mtx)
pickle.dump(imputed_acc_obj)
```

Could that have been the issue?

**Comment by alexlenail** [comment]
I turned the normalized matrix into a dense matrix, and the function worked. Could it be that that this code path was never tested, 

https://github.com/aertslab/pycisTopic/blob/219225df56b32738d82cd14532b187a1483de04f/pycisTopic/diff_features.py#L106

and `find_diff_features` doesn't work on sparse matrices?

**Comment by ghuls** [comment]
`impute_accessibility` and `normalize_scores` have been rewritten and will not write sparse matrices anymore (as it almost never would save a lot of memory and would slowdown further calculations too much.
Memory usage an running time went down also quite significantly.
See https://github.com/aertslab/pycisTopic/pull/77 for more details.

`find_diff_features` is now being rewritten and will use less memory and will be much faster (especially when not using a sparse matrix as input:
See https://github.com/aertslab/pycisTopic/pull/78

**Comment by yojetsharma** [comment]
I’m using the latest pycisTopic version and get an error of memory allocation of 170GiB on a cluster with 250GiB RAM after running the `find_highly_variable_features`. Please help
