### ISSUE TITLE
Bug report [Error in building Docker image]

### ISSUE THREAD

**Issue by QuanEvans** [aertslab/pycisTopic#72]
**Describe the bug**
An error occurs when building a Docker image due to an incorrect version specifier in the setup.py file of the MACS2 package.

**To Reproduce**
Clone the repositories and set up the environment.
Attempt to build the Docker image using the provided Dockerfile.

**Error output**
error in MACS2 setup command: 
Collecting MACS2
  Downloading MACS2-2.2.7.1.tar.gz (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 5.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [4 lines of output]
      Requirement already satisfied: numpy>=1.17 in /tmp/pip-build-env-kmlcao_7/overlay/lib/python3.8/site-packages (1.24.2)
      error in MACS2 setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after name and no valid version specifier)
          numpy>=>=1.17
               ^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
[2/2] STEP 1/6: FROM python:3.8-slim AS build-image
Error: error building at STEP "RUN pip install --no-cache-dir --upgrade pip wheel &&     pip install --no-cache-dir numpy==1.22 &&     pip install --no-cache-dir MACS2 &&     pip install --no-cache-dir scipy==1.8.0 &&     pip install --no-cache-dir Cython &&     pip install --no-cache-dir fitsne &&     pip install --no-cache-dir papermill &&     pip install --no-cache-dir igv_jupyterlab &&     pip install --no-cache-dir bs4 &&     pip install --no-cache-dir lxml &&     pip install --no-cache-dir tspex &&     pip install --no-cache-dir plotly &&     pip install --no-cache-dir kaleido &&     pip install --no-cache-dir pyvis &&     pip install velocyto &&     pip install --no-cache-dir pygam &&     pip install --no-cache-dir fa2 &&     pip install --no-cache-dir scanpy==1.8.2 &&     pip install --no-cache-dir -r /tmp/requirements.txt": error while running runtime: exit status 1

**Expected behavior**
The Docker image should build without any errors.

**Version (please complete the following information):**
 - Python: 3.9
 - MACS2 2.2.7.1

**Additional context**
The following line in MACS2 setup.py have problems
line 19: numpy_requires = '>=1.17'
line 20: install_requires = [f"numpy>={numpy_requires}",]
Removing one of the >= would solve the problem.

**Comment by SeppeDeWinter** [comment]
Hi @QuanEvans 

We should update to MACS3... 

In the mean time you can use this patch: https://github.com/aertslab/scenicplus/issues/101.

Best,

Seppe

**Comment by midichlorianrich** [comment]
I had a similar issue pip installing MACS2-2.2.7.1. However, conda install worked.
