### ISSUE TITLE
Bug report [BUG] read_csv() got an unexpected keyword argument 'sep'

### ISSUE THREAD

**Issue by li-xuyang28** [aertslab/pycisTopic#74]
I am trying to run pycisTopic in colab, and got the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-24-3f1d0ab52ead>](https://localhost:8080/#) in <cell line: 13>()
     11 path_to_regions = {'10x_pbmc':os.path.join(work_dir, 'scATAC/consensus_peak_calling/consensus_regions.bed')}
     12 
---> 13 metadata_bc, profile_data_dict = compute_qc_stats(
     14                 fragments_dict = fragments_dict,
     15                 tss_annotation = annot,

3 frames
[/usr/local/lib/python3.9/dist-packages/pycisTopic/utils.py](https://localhost:8080/#) in read_fragments_from_file(fragments_bed_filename, use_polars)
    393         # Read fragments BED file with polars.
    394         df = (
--> 395             pl.read_csv(
    396                 fragments_bed_filename,
    397                 has_header=False,

TypeError: read_csv() got an unexpected keyword argument 'sep'

It seems that the current version of pl doesn't have the argument sep in read_csv() anymore, and the use_polars = False argument in compute_qc_stats doesn't seem to be communicated to read_fragments.

**Comment by ghuls** [comment]
Both should be fixed in the master now.

**Comment by ghuls** [comment]
Closing as it is fixed.
