### ISSUE TITLE
pycisTopic/Scenic+ human cerebellum single-cell multiome tutorial issue

### ISSUE THREAD

**Issue by etiennedanis** [aertslab/pycisTopic#75]
Hello,
Thank you very much for creating pycisTopic and Scenic+!
I'm trying to learn how to use Scenic+ with your tutorial.
To do so, I need pkl files generated with the pycisTopic tutorial.
In this pycisTopic tutorial, you mention that the loom files are available at: https://scope.aertslab.org/#/scenic-v2
The file you use for annotation is: "10x_multiome_brain_Seurat.loom".
On the https://scope.aertslab.org/#/scenic-v2 website, I only found the following loom files:
HC_gene_based.loom
HC_region_based.loom
10x_multiome_brain_pycisTopic_region_accessibility.loom
10x_multiome_brain_pycisTopic_gene_expression_v2.loom
10x_multiome_brain_pycisTopic_gene_activity_v2.loom
10X_brain_visium.loom
Could you please help me get access to the '10x_multiome_brain_Seurat.loom' file?

I checked whether any of the other loom files would work and they do have similar column names but they do not have the same number of rows. The '10x_multiome_brain_Seurat.loom' has 2,392 rows/barcodes while the other files have much less (the max I found was 1,736).

I am asking about this '10x_multiome_brain_Seurat.loom' file because down the line, after generating the pseudobulk files, inferring the consensus peaks, starting the QC step, I don't get the same results than those obtained in your online tutorial.
I get this: 
![image](https://user-images.githubusercontent.com/11301740/233696641-ed5a4f6f-1766-41d3-a69b-69bee1f39264.png)
Instead of this:
![image](https://user-images.githubusercontent.com/11301740/233696772-42a12ecb-b53f-412a-8ae4-d80475496924.png)
(The major difference is in the 3rd plot from the left)

I also get this:
![image](https://user-images.githubusercontent.com/11301740/233696875-61829fe2-3861-4abc-afec-4ec736685cfd.png)

Instead of this:
![image](https://user-images.githubusercontent.com/11301740/233697041-8311b325-14cb-438e-9d2d-1be660ebb06d.png)

And instead of getting 2,925 selected barcodes, I get 0 barcodes passing the QC filtering.

I copied and pasted the codes you provided.
I'm wondering whether it is an issue of not having the correct annotation/loom file or it is an issue related to the installation of the tools (could some of the tools I just installed depend on new versions of other tools that would affect the analysis) or something else.

If you could help, it would be greatly appreciated.
Thank you very much in advance.
Etienne

**Comment by SeppeDeWinter** [comment]
Hi @etiennedanis 

Indeed something seems wrong here.

You seem to have way less barcodes... Are you sure you downloaded the entire fragment file?
How many rows does your fragments file have? Should be `152844735`

Here you can find a download link for the loom file in question:
https://cloud.aertslab.org/index.php/s/5TgtSdEPXygPLX9

Best,

Seppe

**Comment by SeppeDeWinter** [comment]
Hi @etiennedanis 

It was an issue with pandas version 2.0.1, see https://github.com/aertslab/scenicplus/issues/146#issuecomment-1538351802.
