### ISSUE TITLE
`valid_bc` argument for `barcode_rank_function` has unanticipated behavior

### ISSUE THREAD

**Issue by adamklie** [aertslab/pycisTopic#90]
**Describe the bug**
Not 100% sure if this is a bug, but wanted to bring it up. The `barcode_rank_plot` function has a parameter for `valid_bc` which I interpreted as a place to input a list of string barcodes to consider for the plot. Looking at the code for this function, it looks like it is just used to select the top number of barcodes for plot based on fragment number, similar to giving the actual number in the `n_bc` argument. 

Normally, this would be pretty innocuous, but this did some confusing things for me when I used it as part of the `compute_qc_stats_single` function. This is because that function calls `barcode_rank_plot` and uses the return data downstream. This return data contains the top `len(valid_bc)` barcodes in terms of number of fragments, rather than the actual barcodes I pass in. When the following code is then run:

```python
if valid_bc is None:
      fragments_df = fragments_df[
          fragments_df.Name.isin(set(metrics["barcode_rank_plot"]["valid_bc"]))
      ]
```
The `fragments_df` is subset to down to cells that may not be contained in the initial `valid_bc` input (in fact in my case it only contained 12 of those cells and ~2000 other cell barcodes). All the downstream QCs that take in `fragments_df` now end up reporting metrics on a completely different set of barcodes.

**Expected behavior**
Thinking about it, it probably doesn't make sense to pass a list of string barcodes into the barcode rank plot since they likely will be out of order if they were selected by some criteria other than number of fragments they contain. I actually think the root cause of my confusion is with some mislabeled "high quality" cells (hence only 12 barcodes showing up in the top ~2000 ranked by fragments), so I'm guessing most users won't actually need to worry about this, but in my case it led to more confusion instead of clarity.

The simple fix for the downstream QCs would seem to be to change the above code to the following:
```python
if valid_bc is None:
      fragments_df = fragments_df[
          fragments_df.Name.isin(set(valid_bc))
      ]
```
This would do the filtering on the desired barcodes instead of just on the top ones sorted by number of fragments.

Hopefully this makes sense! Love the package 😃

**Comment by ghuls** [comment]
The QC part of pycisTopic is in the process of a rewrite in the `polars` branch, which cleanup the QC code quite a bit and makes it a lot faster.

**Comment by adamklie** [comment]
Fantastic. I'll stop rifling through it then :) 

Would you say it's ready for beta testing? Would be happy to give it a go.

**Comment by ghuls** [comment]
> Would you say it's ready for beta testing? Would be happy to give it a go.

Unfortunately not yet.

**Comment by adamklie** [comment]
No worries. If you end up needing beta testers, I'm happy to be one!

**Comment by ghuls** [comment]
@adamklie You can test it now if you want.
For now you still need to install pycisTopic from the polars branch till we switch the main branch:
https://pycistopic.readthedocs.io/en/polars/notebooks/human_cerebellum.html#QC

Let us know how it goes.
